TIMEFORMAT=%R
# set to print out real time in seconds
# time <command> will print seconds

OPTARRAY=( "-O0" "-O1" "-O2" "-O3" \
"-O1 -fcse-follow-jumps -ftree-vrp -freorder-blocks -falign-functions -fcse-skip-blocks -ftree-pre -fsched-interblock -fstrict-aliasing -fcrossjumping -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fcse-follow-jumps -ftree-vrp -freorder-blocks -falign-functions -fcse-skip-blocks -ftree-pre -fsched-interblock -fstrict-aliasing -fcrossjumping -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fcse-follow-jumps -ftree-vrp -freorder-blocks -falign-functions -fcse-skip-blocks -ftree-pre -fsched-interblock -fstrict-aliasing -fcrossjumping -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fcse-follow-jumps -ftree-vrp -freorder-blocks -falign-functions -fcse-skip-blocks -ftree-pre -fsched-interblock -fstrict-aliasing -fcrossjumping -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fcse-follow-jumps -ftree-vrp -freorder-blocks -falign-functions -fcse-skip-blocks -ftree-pre -fsched-interblock -fstrict-aliasing -fcrossjumping -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fcrossjumping -freorder-functions -fregmove -fsched-spec -falign-labels -freorder-blocks -fcaller-saves -fsched-interblock -ftree-pre -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fcrossjumping -freorder-functions -fregmove -fsched-spec -falign-labels -freorder-blocks -fcaller-saves -fsched-interblock -ftree-pre -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fcrossjumping -freorder-functions -fregmove -fsched-spec -falign-labels -freorder-blocks -fcaller-saves -fsched-interblock -ftree-pre -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fcrossjumping -freorder-functions -fregmove -fsched-spec -falign-labels -freorder-blocks -fcaller-saves -fsched-interblock -ftree-pre -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fcrossjumping -freorder-functions -fregmove -fsched-spec -falign-labels -freorder-blocks -fcaller-saves -fsched-interblock -ftree-pre -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fregmove -fcrossjumping -fthread-jumps -falign-loops -fschedule-insns2 -freorder-blocks -fsched-interblock -ftree-switch-conversion -fstrict-overflow -fpeephole2 -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fregmove -fcrossjumping -fthread-jumps -falign-loops -fschedule-insns2 -freorder-blocks -fsched-interblock -ftree-switch-conversion -fstrict-overflow -fpeephole2 -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fregmove -fcrossjumping -fthread-jumps -falign-loops -fschedule-insns2 -freorder-blocks -fsched-interblock -ftree-switch-conversion -fstrict-overflow -fpeephole2 -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fregmove -fcrossjumping -fthread-jumps -falign-loops -fschedule-insns2 -freorder-blocks -fsched-interblock -ftree-switch-conversion -fstrict-overflow -fpeephole2 -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fregmove -fcrossjumping -fthread-jumps -falign-loops -fschedule-insns2 -freorder-blocks -fsched-interblock -ftree-switch-conversion -fstrict-overflow -fpeephole2 -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fschedule-insns2 -fsched-spec -fthread-jumps -freorder-blocks -fgcse-lm -frerun-cse-after-loop -ftree-pre -fcse-follow-jumps -fstrict-overflow -falign-labels -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fschedule-insns2 -fsched-spec -fthread-jumps -freorder-blocks -fgcse-lm -frerun-cse-after-loop -ftree-pre -fcse-follow-jumps -fstrict-overflow -falign-labels -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fschedule-insns2 -fsched-spec -fthread-jumps -freorder-blocks -fgcse-lm -frerun-cse-after-loop -ftree-pre -fcse-follow-jumps -fstrict-overflow -falign-labels -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fschedule-insns2 -fsched-spec -fthread-jumps -freorder-blocks -fgcse-lm -frerun-cse-after-loop -ftree-pre -fcse-follow-jumps -fstrict-overflow -falign-labels -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fschedule-insns2 -fsched-spec -fthread-jumps -freorder-blocks -fgcse-lm -frerun-cse-after-loop -ftree-pre -fcse-follow-jumps -fstrict-overflow -falign-labels -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fstrict-overflow -fgcse-lm -fsched-spec -fcse-skip-blocks -fexpensive-optimizations -freorder-functions -fpeephole2 -fdelete-null-pointer-checks -ftree-pre -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fstrict-overflow -fgcse-lm -fsched-spec -fcse-skip-blocks -fexpensive-optimizations -freorder-functions -fpeephole2 -fdelete-null-pointer-checks -ftree-pre -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fstrict-overflow -fgcse-lm -fsched-spec -fcse-skip-blocks -fexpensive-optimizations -freorder-functions -fpeephole2 -fdelete-null-pointer-checks -ftree-pre -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fstrict-overflow -fgcse-lm -fsched-spec -fcse-skip-blocks -fexpensive-optimizations -freorder-functions -fpeephole2 -fdelete-null-pointer-checks -ftree-pre -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fstrict-overflow -fgcse-lm -fsched-spec -fcse-skip-blocks -fexpensive-optimizations -freorder-functions -fpeephole2 -fdelete-null-pointer-checks -ftree-pre -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fsched-spec -frerun-cse-after-loop -freorder-functions -fcaller-saves -falign-functions -findirect-inlining -fgcse-lm -freorder-blocks -falign-labels -fstrict-overflow -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fsched-spec -frerun-cse-after-loop -freorder-functions -fcaller-saves -falign-functions -findirect-inlining -fgcse-lm -freorder-blocks -falign-labels -fstrict-overflow -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fsched-spec -frerun-cse-after-loop -freorder-functions -fcaller-saves -falign-functions -findirect-inlining -fgcse-lm -freorder-blocks -falign-labels -fstrict-overflow -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fsched-spec -frerun-cse-after-loop -freorder-functions -fcaller-saves -falign-functions -findirect-inlining -fgcse-lm -freorder-blocks -falign-labels -fstrict-overflow -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fsched-spec -frerun-cse-after-loop -freorder-functions -fcaller-saves -falign-functions -findirect-inlining -fgcse-lm -freorder-blocks -falign-labels -fstrict-overflow -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fexpensive-optimizations -fgcse-lm -fgcse -fcse-skip-blocks -findirect-inlining -fdelete-null-pointer-checks -fcrossjumping -ftree-pre -ftree-vrp -fschedule-insns2 -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fexpensive-optimizations -fgcse-lm -fgcse -fcse-skip-blocks -findirect-inlining -fdelete-null-pointer-checks -fcrossjumping -ftree-pre -ftree-vrp -fschedule-insns2 -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fexpensive-optimizations -fgcse-lm -fgcse -fcse-skip-blocks -findirect-inlining -fdelete-null-pointer-checks -fcrossjumping -ftree-pre -ftree-vrp -fschedule-insns2 -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fexpensive-optimizations -fgcse-lm -fgcse -fcse-skip-blocks -findirect-inlining -fdelete-null-pointer-checks -fcrossjumping -ftree-pre -ftree-vrp -fschedule-insns2 -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fexpensive-optimizations -fgcse-lm -fgcse -fcse-skip-blocks -findirect-inlining -fdelete-null-pointer-checks -fcrossjumping -ftree-pre -ftree-vrp -fschedule-insns2 -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fdelete-null-pointer-checks -falign-labels -ftree-switch-conversion -findirect-inlining -fthread-jumps -fcaller-saves -fexpensive-optimizations -fsched-spec -fstrict-aliasing -fsched-interblock -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fdelete-null-pointer-checks -falign-labels -ftree-switch-conversion -findirect-inlining -fthread-jumps -fcaller-saves -fexpensive-optimizations -fsched-spec -fstrict-aliasing -fsched-interblock -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fdelete-null-pointer-checks -falign-labels -ftree-switch-conversion -findirect-inlining -fthread-jumps -fcaller-saves -fexpensive-optimizations -fsched-spec -fstrict-aliasing -fsched-interblock -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fdelete-null-pointer-checks -falign-labels -ftree-switch-conversion -findirect-inlining -fthread-jumps -fcaller-saves -fexpensive-optimizations -fsched-spec -fstrict-aliasing -fsched-interblock -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fdelete-null-pointer-checks -falign-labels -ftree-switch-conversion -findirect-inlining -fthread-jumps -fcaller-saves -fexpensive-optimizations -fsched-spec -fstrict-aliasing -fsched-interblock -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fcaller-saves -fcse-follow-jumps -falign-functions -frerun-cse-after-loop -freorder-functions -ftree-vrp -fcse-skip-blocks -fpeephole2 -fgcse -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fcaller-saves -fcse-follow-jumps -falign-functions -frerun-cse-after-loop -freorder-functions -ftree-vrp -fcse-skip-blocks -fpeephole2 -fgcse -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fcaller-saves -fcse-follow-jumps -falign-functions -frerun-cse-after-loop -freorder-functions -ftree-vrp -fcse-skip-blocks -fpeephole2 -fgcse -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fcaller-saves -fcse-follow-jumps -falign-functions -frerun-cse-after-loop -freorder-functions -ftree-vrp -fcse-skip-blocks -fpeephole2 -fgcse -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fcaller-saves -fcse-follow-jumps -falign-functions -frerun-cse-after-loop -freorder-functions -ftree-vrp -fcse-skip-blocks -fpeephole2 -fgcse -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -frerun-cse-after-loop -fpeephole2 -ftree-vrp -findirect-inlining -fregmove -foptimize-sibling-calls -fdelete-null-pointer-checks -fexpensive-optimizations -fgcse -fgcse-lm -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -frerun-cse-after-loop -fpeephole2 -ftree-vrp -findirect-inlining -fregmove -foptimize-sibling-calls -fdelete-null-pointer-checks -fexpensive-optimizations -fgcse -fgcse-lm -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -frerun-cse-after-loop -fpeephole2 -ftree-vrp -findirect-inlining -fregmove -foptimize-sibling-calls -fdelete-null-pointer-checks -fexpensive-optimizations -fgcse -fgcse-lm -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -frerun-cse-after-loop -fpeephole2 -ftree-vrp -findirect-inlining -fregmove -foptimize-sibling-calls -fdelete-null-pointer-checks -fexpensive-optimizations -fgcse -fgcse-lm -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -frerun-cse-after-loop -fpeephole2 -ftree-vrp -findirect-inlining -fregmove -foptimize-sibling-calls -fdelete-null-pointer-checks -fexpensive-optimizations -fgcse -fgcse-lm -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -falign-loops -fthread-jumps -fsched-spec -fstrict-aliasing -fcrossjumping -fschedule-insns2 -freorder-blocks -falign-jumps -findirect-inlining -fsched-interblock -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -falign-loops -fthread-jumps -fsched-spec -fstrict-aliasing -fcrossjumping -fschedule-insns2 -freorder-blocks -falign-jumps -findirect-inlining -fsched-interblock -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -falign-loops -fthread-jumps -fsched-spec -fstrict-aliasing -fcrossjumping -fschedule-insns2 -freorder-blocks -falign-jumps -findirect-inlining -fsched-interblock -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -falign-loops -fthread-jumps -fsched-spec -fstrict-aliasing -fcrossjumping -fschedule-insns2 -freorder-blocks -falign-jumps -findirect-inlining -fsched-interblock -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -falign-loops -fthread-jumps -fsched-spec -fstrict-aliasing -fcrossjumping -fschedule-insns2 -freorder-blocks -falign-jumps -findirect-inlining -fsched-interblock -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -falign-loops -fregmove -ftree-switch-conversion -falign-jumps -fgcse-lm -ftree-vrp -fdelete-null-pointer-checks -fstrict-aliasing -fschedule-insns2 -freorder-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -falign-loops -fregmove -ftree-switch-conversion -falign-jumps -fgcse-lm -ftree-vrp -fdelete-null-pointer-checks -fstrict-aliasing -fschedule-insns2 -freorder-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -falign-loops -fregmove -ftree-switch-conversion -falign-jumps -fgcse-lm -ftree-vrp -fdelete-null-pointer-checks -fstrict-aliasing -fschedule-insns2 -freorder-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -falign-loops -fregmove -ftree-switch-conversion -falign-jumps -fgcse-lm -ftree-vrp -fdelete-null-pointer-checks -fstrict-aliasing -fschedule-insns2 -freorder-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -falign-loops -fregmove -ftree-switch-conversion -falign-jumps -fgcse-lm -ftree-vrp -fdelete-null-pointer-checks -fstrict-aliasing -fschedule-insns2 -freorder-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fschedule-insns2 -freorder-blocks -fgcse-lm -fcaller-saves -ftree-pre -foptimize-sibling-calls -falign-loops -fthread-jumps -freorder-functions -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fschedule-insns2 -freorder-blocks -fgcse-lm -fcaller-saves -ftree-pre -foptimize-sibling-calls -falign-loops -fthread-jumps -freorder-functions -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fschedule-insns2 -freorder-blocks -fgcse-lm -fcaller-saves -ftree-pre -foptimize-sibling-calls -falign-loops -fthread-jumps -freorder-functions -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fschedule-insns2 -freorder-blocks -fgcse-lm -fcaller-saves -ftree-pre -foptimize-sibling-calls -falign-loops -fthread-jumps -freorder-functions -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fschedule-insns2 -freorder-blocks -fgcse-lm -fcaller-saves -ftree-pre -foptimize-sibling-calls -falign-loops -fthread-jumps -freorder-functions -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -ftree-switch-conversion -fsched-spec -ftree-pre -falign-jumps -falign-functions -falign-loops -fcse-skip-blocks -fregmove -fexpensive-optimizations -freorder-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -ftree-switch-conversion -fsched-spec -ftree-pre -falign-jumps -falign-functions -falign-loops -fcse-skip-blocks -fregmove -fexpensive-optimizations -freorder-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -ftree-switch-conversion -fsched-spec -ftree-pre -falign-jumps -falign-functions -falign-loops -fcse-skip-blocks -fregmove -fexpensive-optimizations -freorder-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -ftree-switch-conversion -fsched-spec -ftree-pre -falign-jumps -falign-functions -falign-loops -fcse-skip-blocks -fregmove -fexpensive-optimizations -freorder-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -ftree-switch-conversion -fsched-spec -ftree-pre -falign-jumps -falign-functions -falign-loops -fcse-skip-blocks -fregmove -fexpensive-optimizations -freorder-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fcrossjumping -findirect-inlining -ftree-vrp -fgcse-lm -falign-functions -fschedule-insns2 -fstrict-aliasing -fcaller-saves -ftree-switch-conversion -falign-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fcrossjumping -findirect-inlining -ftree-vrp -fgcse-lm -falign-functions -fschedule-insns2 -fstrict-aliasing -fcaller-saves -ftree-switch-conversion -falign-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fcrossjumping -findirect-inlining -ftree-vrp -fgcse-lm -falign-functions -fschedule-insns2 -fstrict-aliasing -fcaller-saves -ftree-switch-conversion -falign-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fcrossjumping -findirect-inlining -ftree-vrp -fgcse-lm -falign-functions -fschedule-insns2 -fstrict-aliasing -fcaller-saves -ftree-switch-conversion -falign-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fcrossjumping -findirect-inlining -ftree-vrp -fgcse-lm -falign-functions -fschedule-insns2 -fstrict-aliasing -fcaller-saves -ftree-switch-conversion -falign-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fregmove -falign-loops -fthread-jumps -ftree-switch-conversion -fcse-follow-jumps -findirect-inlining -fsched-spec -fgcse -fdelete-null-pointer-checks -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fregmove -falign-loops -fthread-jumps -ftree-switch-conversion -fcse-follow-jumps -findirect-inlining -fsched-spec -fgcse -fdelete-null-pointer-checks -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fregmove -falign-loops -fthread-jumps -ftree-switch-conversion -fcse-follow-jumps -findirect-inlining -fsched-spec -fgcse -fdelete-null-pointer-checks -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fregmove -falign-loops -fthread-jumps -ftree-switch-conversion -fcse-follow-jumps -findirect-inlining -fsched-spec -fgcse -fdelete-null-pointer-checks -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fregmove -falign-loops -fthread-jumps -ftree-switch-conversion -fcse-follow-jumps -findirect-inlining -fsched-spec -fgcse -fdelete-null-pointer-checks -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fgcse -fsched-interblock -ftree-vrp -falign-functions -falign-labels -fstrict-aliasing -fcse-follow-jumps -fsched-spec -ftree-switch-conversion -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fgcse -fsched-interblock -ftree-vrp -falign-functions -falign-labels -fstrict-aliasing -fcse-follow-jumps -fsched-spec -ftree-switch-conversion -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fgcse -fsched-interblock -ftree-vrp -falign-functions -falign-labels -fstrict-aliasing -fcse-follow-jumps -fsched-spec -ftree-switch-conversion -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fgcse -fsched-interblock -ftree-vrp -falign-functions -falign-labels -fstrict-aliasing -fcse-follow-jumps -fsched-spec -ftree-switch-conversion -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fgcse -fsched-interblock -ftree-vrp -falign-functions -falign-labels -fstrict-aliasing -fcse-follow-jumps -fsched-spec -ftree-switch-conversion -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fthread-jumps -fcse-skip-blocks -fgcse -ftree-pre -fsched-interblock -findirect-inlining -falign-functions -fdelete-null-pointer-checks -fstrict-overflow -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fthread-jumps -fcse-skip-blocks -fgcse -ftree-pre -fsched-interblock -findirect-inlining -falign-functions -fdelete-null-pointer-checks -fstrict-overflow -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fthread-jumps -fcse-skip-blocks -fgcse -ftree-pre -fsched-interblock -findirect-inlining -falign-functions -fdelete-null-pointer-checks -fstrict-overflow -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fthread-jumps -fcse-skip-blocks -fgcse -ftree-pre -fsched-interblock -findirect-inlining -falign-functions -fdelete-null-pointer-checks -fstrict-overflow -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fthread-jumps -fcse-skip-blocks -fgcse -ftree-pre -fsched-interblock -findirect-inlining -falign-functions -fdelete-null-pointer-checks -fstrict-overflow -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -frerun-cse-after-loop -fschedule-insns2 -freorder-functions -findirect-inlining -fsched-interblock -fregmove -freorder-blocks -fsched-spec -fpeephole2 -ftree-vrp -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -frerun-cse-after-loop -fschedule-insns2 -freorder-functions -findirect-inlining -fsched-interblock -fregmove -freorder-blocks -fsched-spec -fpeephole2 -ftree-vrp -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -frerun-cse-after-loop -fschedule-insns2 -freorder-functions -findirect-inlining -fsched-interblock -fregmove -freorder-blocks -fsched-spec -fpeephole2 -ftree-vrp -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -frerun-cse-after-loop -fschedule-insns2 -freorder-functions -findirect-inlining -fsched-interblock -fregmove -freorder-blocks -fsched-spec -fpeephole2 -ftree-vrp -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -frerun-cse-after-loop -fschedule-insns2 -freorder-functions -findirect-inlining -fsched-interblock -fregmove -freorder-blocks -fsched-spec -fpeephole2 -ftree-vrp -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -falign-labels -fcrossjumping -findirect-inlining -ftree-vrp -ftree-pre -fcse-follow-jumps -fsched-spec -ftree-switch-conversion -fexpensive-optimizations -fgcse-lm -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -falign-labels -fcrossjumping -findirect-inlining -ftree-vrp -ftree-pre -fcse-follow-jumps -fsched-spec -ftree-switch-conversion -fexpensive-optimizations -fgcse-lm -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -falign-labels -fcrossjumping -findirect-inlining -ftree-vrp -ftree-pre -fcse-follow-jumps -fsched-spec -ftree-switch-conversion -fexpensive-optimizations -fgcse-lm -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -falign-labels -fcrossjumping -findirect-inlining -ftree-vrp -ftree-pre -fcse-follow-jumps -fsched-spec -ftree-switch-conversion -fexpensive-optimizations -fgcse-lm -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -falign-labels -fcrossjumping -findirect-inlining -ftree-vrp -ftree-pre -fcse-follow-jumps -fsched-spec -ftree-switch-conversion -fexpensive-optimizations -fgcse-lm -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fstrict-aliasing -fcaller-saves -foptimize-sibling-calls -ftree-switch-conversion -fcrossjumping -fthread-jumps -fdelete-null-pointer-checks -falign-loops -fsched-interblock -falign-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fstrict-aliasing -fcaller-saves -foptimize-sibling-calls -ftree-switch-conversion -fcrossjumping -fthread-jumps -fdelete-null-pointer-checks -falign-loops -fsched-interblock -falign-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fstrict-aliasing -fcaller-saves -foptimize-sibling-calls -ftree-switch-conversion -fcrossjumping -fthread-jumps -fdelete-null-pointer-checks -falign-loops -fsched-interblock -falign-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fstrict-aliasing -fcaller-saves -foptimize-sibling-calls -ftree-switch-conversion -fcrossjumping -fthread-jumps -fdelete-null-pointer-checks -falign-loops -fsched-interblock -falign-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fstrict-aliasing -fcaller-saves -foptimize-sibling-calls -ftree-switch-conversion -fcrossjumping -fthread-jumps -fdelete-null-pointer-checks -falign-loops -fsched-interblock -falign-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fgcse -fcaller-saves -fcse-skip-blocks -falign-labels -fregmove -fpeephole2 -ftree-vrp -freorder-blocks -falign-functions -fdelete-null-pointer-checks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fgcse -fcaller-saves -fcse-skip-blocks -falign-labels -fregmove -fpeephole2 -ftree-vrp -freorder-blocks -falign-functions -fdelete-null-pointer-checks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fgcse -fcaller-saves -fcse-skip-blocks -falign-labels -fregmove -fpeephole2 -ftree-vrp -freorder-blocks -falign-functions -fdelete-null-pointer-checks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fgcse -fcaller-saves -fcse-skip-blocks -falign-labels -fregmove -fpeephole2 -ftree-vrp -freorder-blocks -falign-functions -fdelete-null-pointer-checks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fgcse -fcaller-saves -fcse-skip-blocks -falign-labels -fregmove -fpeephole2 -ftree-vrp -freorder-blocks -falign-functions -fdelete-null-pointer-checks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fgcse-lm -fpeephole2 -fsched-spec -fgcse -falign-jumps -fregmove -fcaller-saves -findirect-inlining -ftree-vrp -freorder-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fgcse-lm -fpeephole2 -fsched-spec -fgcse -falign-jumps -fregmove -fcaller-saves -findirect-inlining -ftree-vrp -freorder-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fgcse-lm -fpeephole2 -fsched-spec -fgcse -falign-jumps -fregmove -fcaller-saves -findirect-inlining -ftree-vrp -freorder-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fgcse-lm -fpeephole2 -fsched-spec -fgcse -falign-jumps -fregmove -fcaller-saves -findirect-inlining -ftree-vrp -freorder-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fgcse-lm -fpeephole2 -fsched-spec -fgcse -falign-jumps -fregmove -fcaller-saves -findirect-inlining -ftree-vrp -freorder-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fcrossjumping -fstrict-overflow -ftree-vrp -freorder-blocks -fdelete-null-pointer-checks -fstrict-aliasing -foptimize-sibling-calls -fcse-skip-blocks -fexpensive-optimizations -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fcrossjumping -fstrict-overflow -ftree-vrp -freorder-blocks -fdelete-null-pointer-checks -fstrict-aliasing -foptimize-sibling-calls -fcse-skip-blocks -fexpensive-optimizations -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fcrossjumping -fstrict-overflow -ftree-vrp -freorder-blocks -fdelete-null-pointer-checks -fstrict-aliasing -foptimize-sibling-calls -fcse-skip-blocks -fexpensive-optimizations -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fcrossjumping -fstrict-overflow -ftree-vrp -freorder-blocks -fdelete-null-pointer-checks -fstrict-aliasing -foptimize-sibling-calls -fcse-skip-blocks -fexpensive-optimizations -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fcrossjumping -fstrict-overflow -ftree-vrp -freorder-blocks -fdelete-null-pointer-checks -fstrict-aliasing -foptimize-sibling-calls -fcse-skip-blocks -fexpensive-optimizations -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -ftree-pre -fthread-jumps -fstrict-overflow -freorder-functions -freorder-blocks -falign-functions -fpeephole2 -fcse-follow-jumps -fgcse -foptimize-sibling-calls -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -ftree-pre -fthread-jumps -fstrict-overflow -freorder-functions -freorder-blocks -falign-functions -fpeephole2 -fcse-follow-jumps -fgcse -foptimize-sibling-calls -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -ftree-pre -fthread-jumps -fstrict-overflow -freorder-functions -freorder-blocks -falign-functions -fpeephole2 -fcse-follow-jumps -fgcse -foptimize-sibling-calls -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -ftree-pre -fthread-jumps -fstrict-overflow -freorder-functions -freorder-blocks -falign-functions -fpeephole2 -fcse-follow-jumps -fgcse -foptimize-sibling-calls -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -ftree-pre -fthread-jumps -fstrict-overflow -freorder-functions -freorder-blocks -falign-functions -fpeephole2 -fcse-follow-jumps -fgcse -foptimize-sibling-calls -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fschedule-insns2 -fstrict-overflow -falign-jumps -fcse-follow-jumps -fstrict-aliasing -freorder-blocks -falign-loops -fcaller-saves -findirect-inlining -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fschedule-insns2 -fstrict-overflow -falign-jumps -fcse-follow-jumps -fstrict-aliasing -freorder-blocks -falign-loops -fcaller-saves -findirect-inlining -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fschedule-insns2 -fstrict-overflow -falign-jumps -fcse-follow-jumps -fstrict-aliasing -freorder-blocks -falign-loops -fcaller-saves -findirect-inlining -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fschedule-insns2 -fstrict-overflow -falign-jumps -fcse-follow-jumps -fstrict-aliasing -freorder-blocks -falign-loops -fcaller-saves -findirect-inlining -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fschedule-insns2 -fstrict-overflow -falign-jumps -fcse-follow-jumps -fstrict-aliasing -freorder-blocks -falign-loops -fcaller-saves -findirect-inlining -fexpensive-optimizations -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -findirect-inlining -fstrict-overflow -ftree-vrp -foptimize-sibling-calls -freorder-functions -fsched-spec -falign-jumps -fcse-follow-jumps -fgcse-lm -fcse-skip-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -findirect-inlining -fstrict-overflow -ftree-vrp -foptimize-sibling-calls -freorder-functions -fsched-spec -falign-jumps -fcse-follow-jumps -fgcse-lm -fcse-skip-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -findirect-inlining -fstrict-overflow -ftree-vrp -foptimize-sibling-calls -freorder-functions -fsched-spec -falign-jumps -fcse-follow-jumps -fgcse-lm -fcse-skip-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -findirect-inlining -fstrict-overflow -ftree-vrp -foptimize-sibling-calls -freorder-functions -fsched-spec -falign-jumps -fcse-follow-jumps -fgcse-lm -fcse-skip-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -findirect-inlining -fstrict-overflow -ftree-vrp -foptimize-sibling-calls -freorder-functions -fsched-spec -falign-jumps -fcse-follow-jumps -fgcse-lm -fcse-skip-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fgcse -fsched-spec -falign-loops -freorder-blocks -fgcse-lm -ftree-switch-conversion -fcrossjumping -fstrict-overflow -ftree-pre -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fgcse -fsched-spec -falign-loops -freorder-blocks -fgcse-lm -ftree-switch-conversion -fcrossjumping -fstrict-overflow -ftree-pre -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fgcse -fsched-spec -falign-loops -freorder-blocks -fgcse-lm -ftree-switch-conversion -fcrossjumping -fstrict-overflow -ftree-pre -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fgcse -fsched-spec -falign-loops -freorder-blocks -fgcse-lm -ftree-switch-conversion -fcrossjumping -fstrict-overflow -ftree-pre -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fgcse -fsched-spec -falign-loops -freorder-blocks -fgcse-lm -ftree-switch-conversion -fcrossjumping -fstrict-overflow -ftree-pre -fthread-jumps -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -falign-labels -findirect-inlining -fgcse-lm -freorder-functions -fregmove -fcse-skip-blocks -foptimize-sibling-calls -falign-loops -frerun-cse-after-loop -fsched-spec -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -falign-labels -findirect-inlining -fgcse-lm -freorder-functions -fregmove -fcse-skip-blocks -foptimize-sibling-calls -falign-loops -frerun-cse-after-loop -fsched-spec -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -falign-labels -findirect-inlining -fgcse-lm -freorder-functions -fregmove -fcse-skip-blocks -foptimize-sibling-calls -falign-loops -frerun-cse-after-loop -fsched-spec -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -falign-labels -findirect-inlining -fgcse-lm -freorder-functions -fregmove -fcse-skip-blocks -foptimize-sibling-calls -falign-loops -frerun-cse-after-loop -fsched-spec -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -falign-labels -findirect-inlining -fgcse-lm -freorder-functions -fregmove -fcse-skip-blocks -foptimize-sibling-calls -falign-loops -frerun-cse-after-loop -fsched-spec -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fexpensive-optimizations -fstrict-aliasing -fschedule-insns2 -fregmove -falign-labels -ftree-pre -freorder-functions -falign-loops -fcaller-saves -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fexpensive-optimizations -fstrict-aliasing -fschedule-insns2 -fregmove -falign-labels -ftree-pre -freorder-functions -falign-loops -fcaller-saves -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fexpensive-optimizations -fstrict-aliasing -fschedule-insns2 -fregmove -falign-labels -ftree-pre -freorder-functions -falign-loops -fcaller-saves -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fexpensive-optimizations -fstrict-aliasing -fschedule-insns2 -fregmove -falign-labels -ftree-pre -freorder-functions -falign-loops -fcaller-saves -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fexpensive-optimizations -fstrict-aliasing -fschedule-insns2 -fregmove -falign-labels -ftree-pre -freorder-functions -falign-loops -fcaller-saves -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -falign-jumps -fcaller-saves -fsched-spec -foptimize-sibling-calls -fcse-follow-jumps -fpeephole2 -freorder-blocks -ftree-switch-conversion -falign-labels -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -falign-jumps -fcaller-saves -fsched-spec -foptimize-sibling-calls -fcse-follow-jumps -fpeephole2 -freorder-blocks -ftree-switch-conversion -falign-labels -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -falign-jumps -fcaller-saves -fsched-spec -foptimize-sibling-calls -fcse-follow-jumps -fpeephole2 -freorder-blocks -ftree-switch-conversion -falign-labels -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -falign-jumps -fcaller-saves -fsched-spec -foptimize-sibling-calls -fcse-follow-jumps -fpeephole2 -freorder-blocks -ftree-switch-conversion -falign-labels -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -falign-jumps -fcaller-saves -fsched-spec -foptimize-sibling-calls -fcse-follow-jumps -fpeephole2 -freorder-blocks -ftree-switch-conversion -falign-labels -frerun-cse-after-loop -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fstrict-aliasing -fcrossjumping -fgcse -falign-labels -ftree-pre -frerun-cse-after-loop -fstrict-overflow -fschedule-insns2 -falign-loops -fdelete-null-pointer-checks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fstrict-aliasing -fcrossjumping -fgcse -falign-labels -ftree-pre -frerun-cse-after-loop -fstrict-overflow -fschedule-insns2 -falign-loops -fdelete-null-pointer-checks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fstrict-aliasing -fcrossjumping -fgcse -falign-labels -ftree-pre -frerun-cse-after-loop -fstrict-overflow -fschedule-insns2 -falign-loops -fdelete-null-pointer-checks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fstrict-aliasing -fcrossjumping -fgcse -falign-labels -ftree-pre -frerun-cse-after-loop -fstrict-overflow -fschedule-insns2 -falign-loops -fdelete-null-pointer-checks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fstrict-aliasing -fcrossjumping -fgcse -falign-labels -ftree-pre -frerun-cse-after-loop -fstrict-overflow -fschedule-insns2 -falign-loops -fdelete-null-pointer-checks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fpeephole2 -findirect-inlining -falign-loops -fsched-spec -freorder-functions -falign-functions -fcrossjumping -ftree-pre -foptimize-sibling-calls -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fpeephole2 -findirect-inlining -falign-loops -fsched-spec -freorder-functions -falign-functions -fcrossjumping -ftree-pre -foptimize-sibling-calls -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fpeephole2 -findirect-inlining -falign-loops -fsched-spec -freorder-functions -falign-functions -fcrossjumping -ftree-pre -foptimize-sibling-calls -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fpeephole2 -findirect-inlining -falign-loops -fsched-spec -freorder-functions -falign-functions -fcrossjumping -ftree-pre -foptimize-sibling-calls -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fpeephole2 -findirect-inlining -falign-loops -fsched-spec -freorder-functions -falign-functions -fcrossjumping -ftree-pre -foptimize-sibling-calls -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -falign-functions -fgcse -fstrict-aliasing -fcrossjumping -freorder-blocks -frerun-cse-after-loop -fexpensive-optimizations -fcse-skip-blocks -freorder-functions -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -falign-functions -fgcse -fstrict-aliasing -fcrossjumping -freorder-blocks -frerun-cse-after-loop -fexpensive-optimizations -fcse-skip-blocks -freorder-functions -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -falign-functions -fgcse -fstrict-aliasing -fcrossjumping -freorder-blocks -frerun-cse-after-loop -fexpensive-optimizations -fcse-skip-blocks -freorder-functions -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -falign-functions -fgcse -fstrict-aliasing -fcrossjumping -freorder-blocks -frerun-cse-after-loop -fexpensive-optimizations -fcse-skip-blocks -freorder-functions -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -falign-functions -fgcse -fstrict-aliasing -fcrossjumping -freorder-blocks -frerun-cse-after-loop -fexpensive-optimizations -fcse-skip-blocks -freorder-functions -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fschedule-insns2 -fcse-skip-blocks -fexpensive-optimizations -fsched-spec -fsched-interblock -ftree-vrp -findirect-inlining -fgcse -fthread-jumps -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fschedule-insns2 -fcse-skip-blocks -fexpensive-optimizations -fsched-spec -fsched-interblock -ftree-vrp -findirect-inlining -fgcse -fthread-jumps -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fschedule-insns2 -fcse-skip-blocks -fexpensive-optimizations -fsched-spec -fsched-interblock -ftree-vrp -findirect-inlining -fgcse -fthread-jumps -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fschedule-insns2 -fcse-skip-blocks -fexpensive-optimizations -fsched-spec -fsched-interblock -ftree-vrp -findirect-inlining -fgcse -fthread-jumps -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fschedule-insns2 -fcse-skip-blocks -fexpensive-optimizations -fsched-spec -fsched-interblock -ftree-vrp -findirect-inlining -fgcse -fthread-jumps -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fsched-interblock -fexpensive-optimizations -falign-loops -freorder-blocks -fstrict-aliasing -ftree-pre -fgcse-lm -fcse-follow-jumps -fgcse -falign-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fsched-interblock -fexpensive-optimizations -falign-loops -freorder-blocks -fstrict-aliasing -ftree-pre -fgcse-lm -fcse-follow-jumps -fgcse -falign-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fsched-interblock -fexpensive-optimizations -falign-loops -freorder-blocks -fstrict-aliasing -ftree-pre -fgcse-lm -fcse-follow-jumps -fgcse -falign-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fsched-interblock -fexpensive-optimizations -falign-loops -freorder-blocks -fstrict-aliasing -ftree-pre -fgcse-lm -fcse-follow-jumps -fgcse -falign-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fsched-interblock -fexpensive-optimizations -falign-loops -freorder-blocks -fstrict-aliasing -ftree-pre -fgcse-lm -fcse-follow-jumps -fgcse -falign-functions -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -fcaller-saves -findirect-inlining -fsched-spec -freorder-blocks -fsched-interblock -fthread-jumps -fexpensive-optimizations -ftree-vrp -fschedule-insns2 -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -fcaller-saves -findirect-inlining -fsched-spec -freorder-blocks -fsched-interblock -fthread-jumps -fexpensive-optimizations -ftree-vrp -fschedule-insns2 -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -fcaller-saves -findirect-inlining -fsched-spec -freorder-blocks -fsched-interblock -fthread-jumps -fexpensive-optimizations -ftree-vrp -fschedule-insns2 -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -fcaller-saves -findirect-inlining -fsched-spec -freorder-blocks -fsched-interblock -fthread-jumps -fexpensive-optimizations -ftree-vrp -fschedule-insns2 -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -fcaller-saves -findirect-inlining -fsched-spec -freorder-blocks -fsched-interblock -fthread-jumps -fexpensive-optimizations -ftree-vrp -fschedule-insns2 -ftree-switch-conversion -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -falign-jumps -fdelete-null-pointer-checks -freorder-blocks -fschedule-insns2 -fcse-skip-blocks -fsched-spec -fstrict-aliasing -fcaller-saves -ftree-vrp -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -falign-jumps -fdelete-null-pointer-checks -freorder-blocks -fschedule-insns2 -fcse-skip-blocks -fsched-spec -fstrict-aliasing -fcaller-saves -ftree-vrp -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -falign-jumps -fdelete-null-pointer-checks -freorder-blocks -fschedule-insns2 -fcse-skip-blocks -fsched-spec -fstrict-aliasing -fcaller-saves -ftree-vrp -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -falign-jumps -fdelete-null-pointer-checks -freorder-blocks -fschedule-insns2 -fcse-skip-blocks -fsched-spec -fstrict-aliasing -fcaller-saves -ftree-vrp -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -falign-jumps -fdelete-null-pointer-checks -freorder-blocks -fschedule-insns2 -fcse-skip-blocks -fsched-spec -fstrict-aliasing -fcaller-saves -ftree-vrp -fregmove -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -falign-functions -fcse-skip-blocks -freorder-blocks -fschedule-insns2 -fexpensive-optimizations -frerun-cse-after-loop -fcaller-saves -fstrict-overflow -ftree-vrp -fcrossjumping -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -falign-functions -fcse-skip-blocks -freorder-blocks -fschedule-insns2 -fexpensive-optimizations -frerun-cse-after-loop -fcaller-saves -fstrict-overflow -ftree-vrp -fcrossjumping -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -falign-functions -fcse-skip-blocks -freorder-blocks -fschedule-insns2 -fexpensive-optimizations -frerun-cse-after-loop -fcaller-saves -fstrict-overflow -ftree-vrp -fcrossjumping -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -falign-functions -fcse-skip-blocks -freorder-blocks -fschedule-insns2 -fexpensive-optimizations -frerun-cse-after-loop -fcaller-saves -fstrict-overflow -ftree-vrp -fcrossjumping -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -falign-functions -fcse-skip-blocks -freorder-blocks -fschedule-insns2 -fexpensive-optimizations -frerun-cse-after-loop -fcaller-saves -fstrict-overflow -ftree-vrp -fcrossjumping -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
"-O1 -falign-labels -falign-functions -fpeephole2 -fregmove -fexpensive-optimizations -foptimize-sibling-calls -findirect-inlining -fgcse -fgcse-lm -fcse-skip-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=2" \
"-O1 -falign-labels -falign-functions -fpeephole2 -fregmove -fexpensive-optimizations -foptimize-sibling-calls -findirect-inlining -fgcse -fgcse-lm -fcse-skip-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=4" \
"-O1 -falign-labels -falign-functions -fpeephole2 -fregmove -fexpensive-optimizations -foptimize-sibling-calls -findirect-inlining -fgcse -fgcse-lm -fcse-skip-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=8" \
"-O1 -falign-labels -falign-functions -fpeephole2 -fregmove -fexpensive-optimizations -foptimize-sibling-calls -findirect-inlining -fgcse -fgcse-lm -fcse-skip-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=16" \
"-O1 -falign-labels -falign-functions -fpeephole2 -fregmove -fexpensive-optimizations -foptimize-sibling-calls -findirect-inlining -fgcse -fgcse-lm -fcse-skip-blocks -finline-functions -funswitch-loops -fpredictive-commoning -fgcse-after-reload -ftree-vectorize -fipa-cp-clone -funroll-loops --param max-unroll-times=32" \
)

BENCHARRAY=( mpeg2dec mpeg2enc )
# done 401.bzip2 429.mcf 433.milc 456.hmmr 457.sjeng 462.libquantum 445.gobmk
#   todo:  464.h264ref  470.lbm  h263dec  h263enc  mpeg2dec  mpeg2enc
COMPTIMES=1
RUNTIMES=10

for dir in "${BENCHARRAY[@]}"
do
	(
		echo $dir
		cd $dir
		rm -f CompileRuntimes
		rm -f BenchRunTimes
		cd src
		for b in "${OPTARRAY[@]}"
		do
			(
				for i in $(seq 1 $COMPTIMES)
				do (
					rm -f mpeg2decode
					rm -f mpeg2encode
					rm -f compile.log
					exec 3>&1 4>&2
					t=$( { time make CFLAGS="$b" 1>&3 2>&4; } 2>&1 ) # captures time only.
					exec 3>&- 4>&-
					mille=$( echo "scale = 4; $t * 1000" | bc )
					echo "NUM: $i Compiled $dir with Optimisation \"$b\" in $mille  milleseconds" >> ../CompileRuntimes
					
							
				)
				done

				for j in $(seq 1 $RUNTIMES)
				do (
					cd ..
					exec 3>&1 4>&2
					time=$( { time ./run.sh 1>&3 2>&4; } 2>&1 )
					exec 3>&- 4>&-
					milles=$( echo "scale = 4; $time * 1000" | bc)
					echo "NUM: $j Ran $dir with Opt \"$b\" in $milles ms" >> BenchRunTimes
					cd src
				)
				done
			cp ../CompileRuntimes ~/co/spec/$dir/CompileRuntimes
			cp ../BenchRunTimes ~co/spec/$dir/BenchRunTimes
			)
		done
		cd ..
		mkdir ~/co/spec/$dir/final/
		cp CompileRuntimes ~/co/spec/$dir/final/CompileRuntimes
		cp BenchRunTimes ~/co/spec/$dir/final/BenchRunTimes
		cd ..
	)
done
cd ..
rm -rf spec

